export const BASE_REPO = 'react-native-community/directory';
export const LIBRARIES_FILE = 'react-native-libraries.json';
export const OXFMT_TMP_CONFIG = '.rnd.oxfmtrc.json';

export const FILE_WARNINGS = [
  '*.iml',
  '*.keystore',
  '*.apinotes',
  '_config.yml',
  '.all-contributorsrc',
  '.babelrc',
  '.buckconfig',
  '.clang-format*',
  '.eslintrc.js',
  '.env',
  '.flowconfig',
  '.gitattributes',
  '.gitkeep',
  '.gitmodules',
  '.licence-config.yaml',
  '.nvmrc',
  '.prettierignore',
  '.prettierrc',
  '.project',
  '.prototools',
  '.release-it.json',
  '.release-please-manifest.json',
  '.releaserc.json',
  '.swiftformat',
  '.swiftlint.yml',
  '.travis.yml',
  '.watchmanconfig',
  '.yarnrc.yml',
  'babel.config.js',
  'eslint.config*.*js',
  'expo-module.config.json',
  'gradle-wrapper.jar',
  'gradlew',
  'gradlew.bat',
  'jest*.config.*js',
  'jsconfig.json',
  'local.properties',
  'manifest-*makeinstall*',
  'metro.config.js',
  'nitro.json',
  'publish.gradle',
  '*prettierrc.js',
  'proguard-rules.pro',
  'react-native.config.*js',
  'renovate.json',
  'rollup.config.js',
  'settings.gradle',
  'spotless.gradle',
  'spm.config.json',
  'tsconfig*.json',
  '*.tsbuildinfo',
  'tsup.config.ts',
  'turbo.json',
  'typedoc.json',
  // LOCK FILES
  'yarn.lock',
  'pnpm-lock.yaml',
  'bun.lock',
  'bun.lockb',
  'package-lock.json',
  'uv.lock',
];

export const DIRECTORY_WARNINGS = [
  '.github',
  '.gradle',
  '.idea',
  '.vs',
  '__tests__',
  '__mocks__',
  'coverage',
  'docs',
  'example',
  'examples',
  'mocks',
  'testing',
];
